version: 2
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
jobs:
  build:
    working_directory: ~/circleci_deployment
    docker:
      - image: circleci/node:10.7.0-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run test:ci
